@startuml

title Conditional - Activity Diagram 

start

:The user enters data about his sleep;
:The system checks if data is correct;

if (Is data correct?) then (Yes)
  :Data is correct!;
else (No)
  :Your data is incorrect!;
endif


stop

@enduml
