@startuml
title Usecase for Information system
left to right direction

actor User
actor Admin
actor Book_author

rectangle Software {
  
  User -- (Read a book)
  User -- (Provide information)
  User -- (Leave comments)
  User -- (Information analysis)
  
  Admin -- (Add a book)
  Admin -- (Drawing up a contract)
  Admin -- (Update recommendations)
  
  Admin <-- (Provide information)
  
  Book_author -- (Drawing up a contract)
  
  (Information analysis) ..> (Authorization) : <<include>>
  (Leave comments) ..> (Authorization) : <<include>>
  (Provide information) ..> (Updating sleep information) : <<include>>
  (Provide information) ..> (Add a book) : <<include>>
  (Updating sleep information) ..> (Authorization) : <<include>>
  (Drawing up a contract) ..> (Add a book) : <<include>>
  (Read a book) ..> (Authorization) : <<include>>
}

@enduml
