@startuml
start

:The user enters data about his sleep;
:The system checks if data is correct;

while (data is correct?) then (No)
  :The data is incorrect;
  backward :The user enters data about his sleep;
endwhile
:The system changes the user's sleep data to the newly entered ones;

@enduml
